runtime: python38

handlers:

  - url: /static
    static_dir: static

  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /FandQ
    static_files: public/FandQ.html
    upload: public/FandQ.html


  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
